/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Conectado_Transporte.Enlace_Transporte;
import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Randy
 */
public class Choferes extends javax.swing.JFrame {

    /**
     * Creates new form Choferes
     */
    Enlace_Transporte micon = new Enlace_Transporte();
    Connection con = micon.conectado();

    public Choferes() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono-kiworks.png")).getImage());
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
        mostrarPlaceHolder();
        txtNifChofer.setEditable(true);
        txtNifChofer.requestFocusInWindow();

    }

    public void mostrarPlaceHolder() {
        //PLACEHOLDERS
        PlaceHolder holder;
        holder = new PlaceHolder(txtNifChofer, "Ingresar NIF");
        holder = new PlaceHolder(txtNombre, "Ingresar Nombre");
        holder = new PlaceHolder(txtApellidos, "Ingresar Apellidos");
        holder = new PlaceHolder(txtDireccion, "Ingresar Dirección");
        holder = new PlaceHolder(txtPoblacion, "Ingresar Población");
        holder = new PlaceHolder(txtTelefono, "Ingresar Teléfono");
        holder = new PlaceHolder(txtSalario, "Ingresar Salario");
        holder = new PlaceHolder(txtBuscar, "Ingresar Búsqueda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChoferes = new javax.swing.JTable();
        pChoferes = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPoblacion = new javax.swing.JTextField();
        txtNifChofer = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Choferes");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblChoferes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblChoferes.setName(""); // NOI18N
        tblChoferes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChoferesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChoferes);

        pChoferes.setBackground(new java.awt.Color(255, 255, 255));
        pChoferes.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        pChoferes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
        });

        jLabel7.setText("SALARIO");

        jLabel2.setText("NOMBRE");

        jLabel3.setText("DIRECCIÓN");

        jLabel4.setText("APELLIDOS");

        jLabel5.setText("TELEFONO");

        jLabel6.setText("POBLACIÓN");

        jLabel1.setText("NIF CHOFER");

        txtNifChofer.setEditable(false);
        txtNifChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNifChoferActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEditar.setText("ACTUALIZAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pChoferesLayout = new javax.swing.GroupLayout(pChoferes);
        pChoferes.setLayout(pChoferesLayout);
        pChoferesLayout.setHorizontalGroup(
            pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChoferesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7))
                    .addGroup(pChoferesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnNuevo)))
                .addGap(20, 20, 20)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPoblacion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNifChofer, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pChoferesLayout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar))
                    .addComponent(txtSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pChoferesLayout.setVerticalGroup(
            pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChoferesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNifChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        jLabel8.setText("BUSCAR");
        jLabel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel8KeyReleased(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insertarDatos() {
        try {
            String SQL = "insert into choferes (NIF_Chofer, Nombre, Apellidos, Direccion, Poblacion, Telefono, Salario) values (?,?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, txtNifChofer.getText());
            pst.setString(2, txtNombre.getText());
            pst.setString(3, txtApellidos.getText());
            pst.setString(4, txtDireccion.getText());
            pst.setString(5, txtPoblacion.getText());
            pst.setString(6, txtTelefono.getText());
            pst.setString(7, txtSalario.getText());
            //int select = cmbMateria.getSeletecIndex();
            //pst.setString(1, cmbMateria.getItemAt(select));
            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro Nuevo");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertar datos");
        }
    }

    public void eliminarDatos() {
        try {
            int fila = tblChoferes.getSelectedRow();
            if (fila > 0) {
                String dao = (String) tblChoferes.getValueAt(fila, 0);
                String SQL = "delete from choferes where NIF_Chofer = " + dao;
                Statement st = con.createStatement();
                int n = st.executeUpdate(SQL);
                JOptionPane.showMessageDialog(null, "Registro eliminado");
            } else {
                JOptionPane.showMessageDialog(null, "Registro NO Seleccionado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en al eliminar " + e.getMessage());
        }
    }

    public void actualizarDatos() {
        try {

            String SQL = "update choferes set Nombre=?, Apellidos=?, Direccion=?, Poblacion=?, Telefono=?, Salario=? where NIF_Chofer = ?";
            int fila = tblChoferes.getSelectedRow();
            String nif = txtNifChofer.getText();
            if (fila > 0) {
                String dao = (String) tblChoferes.getValueAt(fila, 0);
                PreparedStatement pst = con.prepareStatement(SQL);
                pst.setString(1, txtNombre.getText());
                pst.setString(2, txtApellidos.getText());
                pst.setString(3, txtDireccion.getText());
                pst.setString(4, txtPoblacion.getText());
                pst.setString(5, txtTelefono.getText());
                pst.setString(6, txtSalario.getText());
                //int select = cmbMateria.getSeletecIndex();
                //pst.setString(1, cmbMateria.getItemAt(select));
                pst.setString(7, dao);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registro actualizado");
            } else if (nif != null) {
                PreparedStatement pst = con.prepareStatement(SQL);
                pst.setString(7, txtNifChofer.getText());
                pst.setString(1, txtNombre.getText());
                pst.setString(2, txtApellidos.getText());
                pst.setString(3, txtDireccion.getText());
                pst.setString(4, txtPoblacion.getText());
                pst.setString(5, txtTelefono.getText());
                pst.setString(6, txtSalario.getText());
                //int select = cmbMateria.getSeletecIndex();
                //pst.setString(1, cmbMateria.getItemAt(select));
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registro actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "Seleccionar un registro.");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el update " + e.getMessage());
        }
    }

    public void limpiarDatos() {
        // txtNifChofer.setText("");
        txtNombre.setText("");
        txtApellidos.setText("");
        txtDireccion.setText("");
        txtPoblacion.setText("");
        txtTelefono.setText("");
        txtSalario.setText("");
        //cmbMateria.setSelectItem(null);
        txtNombre.requestFocusInWindow();
    }

    public void mostrarDatos() {
        String[] titulos = {"NIF", "Nombre", "Apellidos", "Dirección", "Población", "Teléfono", "Salario"};
        String[] registros = new String[7];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        try {
            String SQL = "SELECT * FROM choferes;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0] = rs.getString("NIF_Chofer");
                registros[1] = rs.getString("Nombre");
                registros[2] = rs.getString("Apellidos");
                registros[3] = rs.getString("Direccion");
                registros[4] = rs.getString("Poblacion");
                registros[5] = rs.getString("Telefono");
                registros[6] = rs.getString("Salario");
                modelo.addRow(registros);
            }
            tblChoferes.setModel(modelo);
            //JOptionPane.showMessageDialog(null, "Consulta realizada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de consulta" + e.getMessage());
        }
    }

    public void filtrarDatos(String valor) {
        String[] titulos = {"NIF", "Nombre", "Apellidos", "Dirección", "Población", "Teléfono", "Salario"};
        String[] registros = new String[7];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        try {
            String SQL = "SELECT * FROM choferes where Nombre like '%" + valor + "%' or Apellidos like'%" + valor + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0] = rs.getString("NIF_Chofer");
                registros[1] = rs.getString("Nombre");
                registros[2] = rs.getString("Apellidos");
                registros[3] = rs.getString("Direccion");
                registros[4] = rs.getString("Poblacion");
                registros[5] = rs.getString("Telefono");
                registros[6] = rs.getString("Salario");
                modelo.addRow(registros);
            }
            tblChoferes.setModel(modelo);
            //JOptionPane.showMessageDialog(null, "Consulta realizada");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de consulta" + e.getMessage());
        }
    }

    private void txtNifChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNifChoferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNifChoferActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        insertarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtNifChofer.setEditable(false);
        btnGuardar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblChoferesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChoferesMouseClicked
        // TODO add your handling code here:
        int filaSelect = tblChoferes.rowAtPoint(evt.getPoint());
        txtNifChofer.setEditable(false);
        txtNifChofer.setText(tblChoferes.getValueAt(filaSelect, 0).toString());
        txtNombre.setText(tblChoferes.getValueAt(filaSelect, 1).toString());
        txtApellidos.setText(tblChoferes.getValueAt(filaSelect, 2).toString());
        txtDireccion.setText(tblChoferes.getValueAt(filaSelect, 3).toString());
        txtPoblacion.setText(tblChoferes.getValueAt(filaSelect, 4).toString());
        txtTelefono.setText(tblChoferes.getValueAt(filaSelect, 5).toString());
        txtSalario.setText(tblChoferes.getValueAt(filaSelect, 6).toString());
        btnGuardar.setEnabled(false);
    }//GEN-LAST:event_tblChoferesMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        actualizarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtNifChofer.setText("");
        txtNifChofer.setEditable(true);
        txtNifChofer.requestFocusInWindow();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        txtNifChofer.setEditable(true);
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtNifChofer.setText("");
        txtNifChofer.requestFocusInWindow();
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jLabel8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel8KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel8KeyReleased

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        filtrarDatos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFocusGained

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Indice verIndice = new Indice();
        verIndice.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choferes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pChoferes;
    private javax.swing.JTable tblChoferes;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNifChofer;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPoblacion;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
