/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Conectado_Transporte.Enlace_Transporte;
import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Randy
 */
public class Paquetes extends javax.swing.JFrame {

    /**
     * Creates new form Choferes
     */
    Enlace_Transporte micon = new Enlace_Transporte();
    Connection con = micon.conectado();

    public Paquetes() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono-kiworks.png")).getImage());
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
        mostrarPlaceHolder();
        txtCodigo.setEditable(true);
        txtCodigo.requestFocusInWindow();
        cmbCodProvincia.removeAllItems();
        cmbNifChofer.removeAllItems();
        mostrarDatosComboBox();
        mostrarDatosComboBox2();

    }

    public void mostrarPlaceHolder() {
        //PLACEHOLDERS
        PlaceHolder holder;
        holder = new PlaceHolder(txtCodigo, "Ingresar Código");
        holder = new PlaceHolder(txtDescripcion, "Ingresar Descripción");
        holder = new PlaceHolder(txtDestinatario, "Ingresar Destinatario");
        holder = new PlaceHolder(txtDestino, "Ingresar Dirección");
        holder = new PlaceHolder(txtBuscar, "Ingresar Búsqueda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaquetes = new javax.swing.JTable();
        pChoferes = new javax.swing.JPanel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDestinatario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        cmbNifChofer = new javax.swing.JComboBox<>();
        cmbCodProvincia = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Paquetes");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPaquetes.setName(""); // NOI18N
        tblPaquetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaquetesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPaquetes);

        pChoferes.setBackground(new java.awt.Color(255, 255, 255));
        pChoferes.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        pChoferes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescripcionFocusGained(evt);
            }
        });

        jLabel2.setText("DESCRIPCION");

        jLabel3.setText("DESTINO");

        jLabel4.setText("DESTINATARIO");

        jLabel5.setText("COD PROVINCIA");

        jLabel6.setText("NIF CHOFER");

        jLabel1.setText("CÓDIGO");

        txtCodigo.setEditable(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEditar.setText("ACTUALIZAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        cmbNifChofer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbCodProvincia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pChoferesLayout = new javax.swing.GroupLayout(pChoferes);
        pChoferes.setLayout(pChoferesLayout);
        pChoferesLayout.setHorizontalGroup(
            pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChoferesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addGroup(pChoferesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnNuevo)))
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pChoferesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDestino, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDestinatario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pChoferesLayout.createSequentialGroup()
                                .addComponent(btnLimpiar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar))))
                    .addGroup(pChoferesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCodProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbNifChofer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pChoferesLayout.setVerticalGroup(
            pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChoferesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbNifChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbCodProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        jLabel8.setText("BUSCAR");
        jLabel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel8KeyReleased(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insertarDatos() {
        try {
            String SQL = "insert into paquetes (Cod_Paquete, Descripcion, Destinatario, Direccion_Destino, NIF_Chofer, Cod_Provincia) values (?,?,?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, txtCodigo.getText());
            pst.setString(2, txtDescripcion.getText());
            pst.setString(3, txtDestinatario.getText());
            pst.setString(4, txtDestino.getText());
            //pst.setString(5, txtNifChofer.getText());
            //pst.setString(6, txtCodProvincia.getText());
            //
            int nifChofer = cmbNifChofer.getSelectedIndex();
            pst.setString(5, cmbNifChofer.getItemAt(nifChofer));
            int codProvincia = cmbCodProvincia.getSelectedIndex();
            pst.setString(6, cmbCodProvincia.getItemAt(codProvincia));
            //
            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro Nuevo");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertar datos");
        }
    }

    public void eliminarDatos() {
        try {
            int fila = tblPaquetes.getSelectedRow();
            if (fila > 0) {
                String dao = (String) tblPaquetes.getValueAt(fila, 0);
                String SQL = "delete from paquetes where Cod_Paquete = " + dao;
                Statement st = con.createStatement();
                int n = st.executeUpdate(SQL);
                JOptionPane.showMessageDialog(null, "Registro eliminado");
            } else {
                JOptionPane.showMessageDialog(null, "Registro NO Seleccionado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en al eliminar " + e.getMessage());
        }
    }

    public void actualizarDatos() {
        try {

            String SQL = "update paquetes set Descripcion=?, Destinatario=?, Direccion_Destino=?, NIF_Chofer=?, Cod_Provincia=? where Cod_Paquete = ?";
            int fila = tblPaquetes.getSelectedRow();
            String nif = txtCodigo.getText();
            if (fila > 0) {
                String dao = (String) tblPaquetes.getValueAt(fila, 0);
                PreparedStatement pst = con.prepareStatement(SQL);
                pst.setString(1, txtDescripcion.getText());
                pst.setString(2, txtDestinatario.getText());
                pst.setString(3, txtDestino.getText());
                //pst.setString(4, txtNifChofer.getText());
                //pst.setString(5, txtCodProvincia.getText());
                //
                int nifChofer = cmbNifChofer.getSelectedIndex();
                pst.setString(4, cmbNifChofer.getItemAt(nifChofer));
                int codProvincia = cmbCodProvincia.getSelectedIndex();
                pst.setString(5, cmbCodProvincia.getItemAt(codProvincia));
                //
                pst.setString(6, dao);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registro actualizado");
            } else if (nif != null) {
                PreparedStatement pst = con.prepareStatement(SQL);
                pst.setString(6, txtCodigo.getText());
                pst.setString(1, txtDescripcion.getText());
                pst.setString(2, txtDestinatario.getText());
                pst.setString(3, txtDestino.getText());
                //pst.setString(4, txtNifChofer.getText());
                //pst.setString(5, txtCodProvincia.getText());
                //
                int nifChofer = cmbNifChofer.getSelectedIndex();
                pst.setString(4, cmbNifChofer.getItemAt(nifChofer));
                int codProvincia = cmbCodProvincia.getSelectedIndex();
                pst.setString(5, cmbCodProvincia.getItemAt(codProvincia));
                //
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registro actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "Seleccionar un registro.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el update " + e.getMessage());
        }
    }

    public void limpiarDatos() {

        txtDescripcion.setText("");
        txtDestinatario.setText("");
        txtDestino.setText("");
        //
        cmbNifChofer.setSelectedItem(null);
        cmbCodProvincia.setSelectedItem(null);
        //
        txtDescripcion.requestFocusInWindow();

    }

    public void mostrarDatos() {
        String[] titulos = {"Cod Paquete", "Descripción", "Destinatario", "Dirección Destino", "NIF Chofer", "Cod Provincia"};
        String[] registros = new String[6];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        try {
            String SQL = "SELECT * FROM paquetes;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0] = rs.getString("Cod_Paquete");
                registros[1] = rs.getString("Descripcion");
                registros[2] = rs.getString("Destinatario");
                registros[3] = rs.getString("Direccion_Destino");
                registros[4] = rs.getString("NIF_Chofer");
                registros[5] = rs.getString("Cod_Provincia");
                modelo.addRow(registros);
            }
            tblPaquetes.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de consulta" + e.getMessage());
        }
    }

    public void mostrarDatosComboBox() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Seleccione Un Elemento");
        try {
            String SQL = "SELECT * FROM paquetes order by NIF_Chofer;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                modelo.addElement(rs.getString("NIF_Chofer"));
            }
            cmbNifChofer.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de consulta" + e.getMessage());
        }
    }
    public void mostrarDatosComboBox2() {
        DefaultComboBoxModel modelo = new DefaultComboBoxModel();
        modelo.addElement("Seleccione Un Elemento");
        try {
            String SQL = "SELECT * FROM paquetes order by Cod_Provincia;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                modelo.addElement(rs.getString("Cod_Provincia"));
            }
            cmbCodProvincia.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de consulta" + e.getMessage());
        }
    }
    
    public void filtrarDatos(String valor) {
        String[] titulos = {"Cod Paquete", "Descripción", "Destinatario", "Dirección Destino", "NIF Chofer", "Cod Provincia"};
        String[] registros = new String[6];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        try {
            String SQL = "SELECT * FROM paquetes where Destinatario like '%" + valor + "%' or NIF_Chofer like'%" + valor + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0] = rs.getString("Cod_Paquete");
                registros[1] = rs.getString("Descripcion");
                registros[2] = rs.getString("Destinatario");
                registros[3] = rs.getString("Direccion_Destino");
                registros[4] = rs.getString("NIF_Chofer");
                registros[5] = rs.getString("Cod_Provincia");
                modelo.addRow(registros);
            }
            tblPaquetes.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de consulta" + e.getMessage());
        }
    }

    private void tblPaquetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaquetesMouseClicked
        // TODO add your handling code here:
        int filaSelect = tblPaquetes.rowAtPoint(evt.getPoint());
        txtCodigo.setEditable(false);
        txtCodigo.setText(tblPaquetes.getValueAt(filaSelect, 0).toString());
        txtDescripcion.setText(tblPaquetes.getValueAt(filaSelect, 1).toString());
        txtDestinatario.setText(tblPaquetes.getValueAt(filaSelect, 2).toString());
        txtDestino.setText(tblPaquetes.getValueAt(filaSelect, 3).toString());
        //txtNifChofer.setText(tblPaquetes.getValueAt(filaSelect, 4).toString());
        //txtCodProvincia.setText(tblPaquetes.getValueAt(filaSelect, 5).toString());
        //
        cmbNifChofer.setSelectedItem(tblPaquetes.getValueAt(filaSelect, 4).toString());
        cmbCodProvincia.setSelectedItem(tblPaquetes.getValueAt(filaSelect, 5).toString());
        //
        btnGuardar.setEnabled(false);
    }//GEN-LAST:event_tblPaquetesMouseClicked

    private void jLabel8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel8KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel8KeyReleased

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        filtrarDatos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Indice verIndice = new Indice();
        verIndice.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        txtCodigo.setEditable(true);
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtCodigo.setText("");
        txtCodigo.requestFocusInWindow();
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        insertarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        actualizarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtCodigo.setText("");
        txtCodigo.setEditable(true);
        txtCodigo.requestFocusInWindow();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtCodigo.setEditable(false);
        btnGuardar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescripcionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paquetes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbCodProvincia;
    private javax.swing.JComboBox<String> cmbNifChofer;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pChoferes;
    private javax.swing.JTable tblPaquetes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDestino;
    // End of variables declaration//GEN-END:variables
}
