/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Conectado_Transporte.Enlace_Transporte;
import com.placeholder.PlaceHolder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Randy
 */
public class Provincias extends javax.swing.JFrame {

    /**
     * Creates new form Choferes
     */
    Enlace_Transporte micon = new Enlace_Transporte();
    Connection con = micon.conectado();

    public Provincias() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../Imagenes/icono-kiworks.png")).getImage());
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(getBackground());
        mostrarDatos();
        mostrarPlaceHolder();
        txtCodProvincia.setEditable(true);
        txtCodProvincia.requestFocusInWindow();

    }

    public void mostrarPlaceHolder() {
        //PLACEHOLDERS
        PlaceHolder holder;
        holder = new PlaceHolder(txtCodProvincia, "Ingresar Matricula");
        holder = new PlaceHolder(txtProvincia, "Ingresar Modelo");
        holder = new PlaceHolder(txtBuscar, "Ingresar Búsqueda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProvincias = new javax.swing.JTable();
        pChoferes = new javax.swing.JPanel();
        txtProvincia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodProvincia = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Provincias");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblProvincias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProvincias.setName(""); // NOI18N
        tblProvincias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProvinciasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProvincias);

        pChoferes.setBackground(new java.awt.Color(255, 255, 255));
        pChoferes.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));
        pChoferes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtProvincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtProvinciaFocusGained(evt);
            }
        });

        jLabel2.setText("PROVINCIA");

        jLabel1.setText("COD PROVINCIA");

        txtCodProvincia.setEditable(false);
        txtCodProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProvinciaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEditar.setText("ACTUALIZAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setText("NUEVO");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pChoferesLayout = new javax.swing.GroupLayout(pChoferes);
        pChoferes.setLayout(pChoferesLayout);
        pChoferesLayout.setHorizontalGroup(
            pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChoferesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(pChoferesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnNuevo)))
                .addGap(20, 20, 20)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodProvincia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pChoferesLayout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pChoferesLayout.setVerticalGroup(
            pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pChoferesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addGroup(pChoferesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar)
                    .addComponent(btnNuevo))
                .addContainerGap())
        );

        jLabel8.setText("BUSCAR");
        jLabel8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jLabel8KeyReleased(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insertarDatos() {
        try {
            String SQL = "insert into provincias (Cod_Provincia, Provincia) values (?,?)";
            PreparedStatement pst = con.prepareStatement(SQL);
            pst.setString(1, txtCodProvincia.getText());
            pst.setString(2, txtProvincia.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro Nuevo");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Insertar datos");
        }
    }

    public void eliminarDatos() {
        try {
            int fila = tblProvincias.getSelectedRow();
            if (fila > 0) {
                String dao = (String) tblProvincias.getValueAt(fila, 0);
                String SQL = "delete from provincias where Cod_Provincia = " + dao;
                Statement st = con.createStatement();
                int n = st.executeUpdate(SQL);
                JOptionPane.showMessageDialog(null, "Registro eliminado");
            } else {
                JOptionPane.showMessageDialog(null, "Registro NO Seleccionado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en al eliminar " + e.getMessage());
        }
    }

    public void actualizarDatos() {
        try {
            String SQL = "update provincias set Provincia=? where Cod_Provincia = ?";
            int fila = tblProvincias.getSelectedRow();
            String nif = txtCodProvincia.getText();
            if (fila > 0) {
                String dao = (String) tblProvincias.getValueAt(fila, 0);
                PreparedStatement pst = con.prepareStatement(SQL);
                pst.setString(1, txtProvincia.getText());
                pst.setString(2, dao);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registro actualizado");
            } else if (nif != null) {
                PreparedStatement pst = con.prepareStatement(SQL);
                pst.setString(2, txtCodProvincia.getText());
                pst.setString(1, txtProvincia.getText());
                pst.execute();
                JOptionPane.showMessageDialog(null, "Registro actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "Seleccionar un registro.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en el update " + e.getMessage());
        }
    }

    public void limpiarDatos() {
        txtProvincia.setText("");
        txtProvincia.requestFocusInWindow();
    }

    public void mostrarDatos() {
        String[] titulos = {"Código Provincia", "Provincia"};
        String[] registros = new String[2];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        try {
            String SQL = "SELECT * FROM provincias;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0] = rs.getString("Cod_Provincia");
                registros[1] = rs.getString("Provincia");
                modelo.addRow(registros);
            }
            tblProvincias.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de consulta" + e.getMessage());
        }
    }

    public void filtrarDatos(String valor) {
        String[] titulos = {"Código Provincia", "Provincia"};
        String[] registros = new String[2];
        DefaultTableModel modelo = new DefaultTableModel(null, titulos);
        try {
            String SQL = "SELECT * FROM provincias where Cod_Provincia like '%" + valor + "%' or Provincia like'%" + valor + "%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                registros[0] = rs.getString("Cod_Provincia");
                registros[1] = rs.getString("Provincia");
                modelo.addRow(registros);
            }
            tblProvincias.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de consulta" + e.getMessage());
        }
    }

    private void txtCodProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProvinciaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        insertarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtCodProvincia.setEditable(false);
        btnGuardar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblProvinciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProvinciasMouseClicked
        // TODO add your handling code here:
        int filaSelect = tblProvincias.rowAtPoint(evt.getPoint());
        txtCodProvincia.setEditable(false);
        txtCodProvincia.setText(tblProvincias.getValueAt(filaSelect, 0).toString());
        txtProvincia.setText(tblProvincias.getValueAt(filaSelect, 1).toString());
        btnGuardar.setEnabled(false);
    }//GEN-LAST:event_tblProvinciasMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        actualizarDatos();
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtCodProvincia.setText("");
        txtCodProvincia.setEditable(true);
        txtCodProvincia.requestFocusInWindow();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        txtCodProvincia.setEditable(true);
        limpiarDatos();
        mostrarDatos();
        mostrarPlaceHolder();
        txtCodProvincia.setText("");
        txtCodProvincia.requestFocusInWindow();
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void jLabel8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel8KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel8KeyReleased

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        filtrarDatos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void txtProvinciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtProvinciaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvinciaFocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Indice verIndice = new Indice();
        verIndice.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provincias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pChoferes;
    private javax.swing.JTable tblProvincias;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodProvincia;
    private javax.swing.JTextField txtProvincia;
    // End of variables declaration//GEN-END:variables
}
